language: node_js
dist: bionic
os:
  - linux
  - osx
  - windows
node_js:
  - "12"
  - "14"
env:
  global:
    - PREBUILD_TARGETS="12.0.0 14.0.0"
    - PREBUILD_ELECTRON_TARGETS="8.0.0 9.0.0"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
- |
  if [ $TRAVIS_OS_NAME = windows ]; then
    export PATH=/c/program\ files/git/mingw64/libexec/git-core:$PATH
  fi
script:
- npm run test
- |
  for target in $PREBUILD_TARGETS; do
    npm run prebuild -- -t $target --arch="x64"
  done
  for target in $PREBUILD_ELECTRON_TARGETS; do
    npm run prebuild -- -t $target --arch="x64" -r electron
  done
jobs:
  include:
    - stage: npm
      deploy:
        provider: npm
        edge: true
        on:
          tags: true
        email: schneefux+npm@schneefux.xyz
        registry: https://npm.pkg.github.com/schneefux
